### ISSUE TITLE
No audio notification

### ISSUE THREAD

**Issue by Gensoo** [Kapps/PoEWhisperNotifier#5]
Audio notification does not play when receiving a whisper.
Using latest release.

**Comment by Kapps** [comment]
Make sure that Settings -> Enable Sound is checked. Other than that, it should work. Note that by default it will only play if your game is minimized or if you're idle.

**Comment by Gensoo** [comment]
Even if I have "notify only when minimized" unchecked the game must still be minimized to hear sound notification?

**Comment by Kapps** [comment]
No, if you have it unchecked it should always play the sound. The main thing I can recommend checking is that you have Enable Sound checked. The code for the playing of sound is super simple and not something I have much control over since it uses the built in .NET stuff (https://github.com/Kapps/PoEWhisperNotifier/blob/master/PoEWhisperNotifier/Main.cs#L136), so it's hard to suggest too much for this. If you're sure you have sounds enabled, make sure Content/notify.wav exists in your PoEWhisperNotifier folder (but atm I think it crashes if it doesn't exist, so this is unlikely to be missing), and that your default sound device in Windows is set properly.

**Comment by Kapps** [comment]
Also, does the Whisper Notifier actually detect you getting a whisper at all? Do you see it in the program window / do you get any notification about it? If not, then this is a separate issue probably cause by the path to the client.txt file being wrong (maybe defaults to the non-Steam version whereas you're playing the Steam version).

**Comment by Gensoo** [comment]
I get tooltip notifications and poewhispernotifier is reading the client.txt, but no sound notifications.
http://a.pomf.cat/czaunt.png
![2015-12-21_02-54-18](https://cloud.githubusercontent.com/assets/9191645/11925929/3ae7d7ca-a78e-11e5-9375-cda72a852da1.png)

**Comment by Kapps** [comment]
That's very strange then. Do you get any error messages in the main window? I can't figure out what the issue would be besides something like the wrong sound device set as default (the Playback device when you go to Control Panel -> Sound), though this would mean other programs play through that other device by default as well. Also, make sure that the notify.wav in the Content folder is actually a valid sound file by playing it in Windows Media Player or similar program, just to make sure it works and isn't corrupt. If this issue only occurs in the whisper notifier, check that the program isn't muted in the Volume Mixer; this seems to happen randomly on Windows sometimes. Rightclick the volume button in your task tray and Open Volume Mixer, make sure PoEWhisperNotifier isn't turned all the way down.

Given that I have virtually no control of anything that the sound player does, I think it's more likely for this to be an issue with some sort of volume or sound card setting. I've double checked, and can't find anywhere that anything could be going wrong, unless the default sound player has a bug in it.

**Comment by Kapps** [comment]
I'm assuming this was fixed, so closing the issue for cleanup.
